//! winit's physical keys (W3C UI Events codes, positional) -> the protocol's
//! keys, which carry the same names.

use pingpong_proto::input::Key;
use winit::keyboard::KeyCode;

pub fn key_for(code: KeyCode) -> Option<Key> {
    Some(match code {
        KeyCode::Escape => Key::Escape,
        KeyCode::Digit1 => Key::Digit1,
        KeyCode::Digit2 => Key::Digit2,
        KeyCode::Digit3 => Key::Digit3,
        KeyCode::Digit4 => Key::Digit4,
        KeyCode::Digit5 => Key::Digit5,
        KeyCode::Digit6 => Key::Digit6,
        KeyCode::Digit7 => Key::Digit7,
        KeyCode::Digit8 => Key::Digit8,
        KeyCode::Digit9 => Key::Digit9,
        KeyCode::Digit0 => Key::Digit0,
        KeyCode::Minus => Key::Minus,
        KeyCode::Equal => Key::Equal,
        KeyCode::Backspace => Key::Backspace,
        KeyCode::Tab => Key::Tab,
        KeyCode::KeyQ => Key::KeyQ,
        KeyCode::KeyW => Key::KeyW,
        KeyCode::KeyE => Key::KeyE,
        KeyCode::KeyR => Key::KeyR,
        KeyCode::KeyT => Key::KeyT,
        KeyCode::KeyY => Key::KeyY,
        KeyCode::KeyU => Key::KeyU,
        KeyCode::KeyI => Key::KeyI,
        KeyCode::KeyO => Key::KeyO,
        KeyCode::KeyP => Key::KeyP,
        KeyCode::BracketLeft => Key::BracketLeft,
        KeyCode::BracketRight => Key::BracketRight,
        KeyCode::Enter => Key::Enter,
        KeyCode::ControlLeft => Key::ControlLeft,
        KeyCode::KeyA => Key::KeyA,
        KeyCode::KeyS => Key::KeyS,
        KeyCode::KeyD => Key::KeyD,
        KeyCode::KeyF => Key::KeyF,
        KeyCode::KeyG => Key::KeyG,
        KeyCode::KeyH => Key::KeyH,
        KeyCode::KeyJ => Key::KeyJ,
        KeyCode::KeyK => Key::KeyK,
        KeyCode::KeyL => Key::KeyL,
        KeyCode::Semicolon => Key::Semicolon,
        KeyCode::Quote => Key::Quote,
        KeyCode::Backquote => Key::Backquote,
        KeyCode::ShiftLeft => Key::ShiftLeft,
        KeyCode::Backslash => Key::Backslash,
        KeyCode::KeyZ => Key::KeyZ,
        KeyCode::KeyX => Key::KeyX,
        KeyCode::KeyC => Key::KeyC,
        KeyCode::KeyV => Key::KeyV,
        KeyCode::KeyB => Key::KeyB,
        KeyCode::KeyN => Key::KeyN,
        KeyCode::KeyM => Key::KeyM,
        KeyCode::Comma => Key::Comma,
        KeyCode::Period => Key::Period,
        KeyCode::Slash => Key::Slash,
        KeyCode::ShiftRight => Key::ShiftRight,
        KeyCode::NumpadMultiply => Key::NumpadMultiply,
        KeyCode::AltLeft => Key::AltLeft,
        KeyCode::Space => Key::Space,
        KeyCode::CapsLock => Key::CapsLock,
        KeyCode::F1 => Key::F1,
        KeyCode::F2 => Key::F2,
        KeyCode::F3 => Key::F3,
        KeyCode::F4 => Key::F4,
        KeyCode::F5 => Key::F5,
        KeyCode::F6 => Key::F6,
        KeyCode::F7 => Key::F7,
        KeyCode::F8 => Key::F8,
        KeyCode::F9 => Key::F9,
        KeyCode::F10 => Key::F10,
        KeyCode::F11 => Key::F11,
        KeyCode::F12 => Key::F12,
        KeyCode::NumLock => Key::NumLock,
        KeyCode::ScrollLock => Key::ScrollLock,
        KeyCode::Numpad0 => Key::Numpad0,
        KeyCode::Numpad1 => Key::Numpad1,
        KeyCode::Numpad2 => Key::Numpad2,
        KeyCode::Numpad3 => Key::Numpad3,
        KeyCode::Numpad4 => Key::Numpad4,
        KeyCode::Numpad5 => Key::Numpad5,
        KeyCode::Numpad6 => Key::Numpad6,
        KeyCode::Numpad7 => Key::Numpad7,
        KeyCode::Numpad8 => Key::Numpad8,
        KeyCode::Numpad9 => Key::Numpad9,
        KeyCode::NumpadSubtract => Key::NumpadSubtract,
        KeyCode::NumpadAdd => Key::NumpadAdd,
        KeyCode::NumpadDecimal => Key::NumpadDecimal,
        KeyCode::NumpadDivide => Key::NumpadDivide,
        KeyCode::NumpadEnter => Key::NumpadEnter,
        KeyCode::IntlBackslash => Key::IntlBackslash,
        KeyCode::ControlRight => Key::ControlRight,
        KeyCode::PrintScreen => Key::PrintScreen,
        KeyCode::AltRight => Key::AltRight,
        KeyCode::Home => Key::Home,
        KeyCode::ArrowUp => Key::ArrowUp,
        KeyCode::PageUp => Key::PageUp,
        KeyCode::ArrowLeft => Key::ArrowLeft,
        KeyCode::ArrowRight => Key::ArrowRight,
        KeyCode::End => Key::End,
        KeyCode::ArrowDown => Key::ArrowDown,
        KeyCode::PageDown => Key::PageDown,
        KeyCode::Insert => Key::Insert,
        KeyCode::Delete => Key::Delete,
        KeyCode::SuperLeft => Key::SuperLeft,
        KeyCode::SuperRight => Key::SuperRight,
        KeyCode::ContextMenu => Key::ContextMenu,
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use pingpong_proto::input::scancode;

    #[test]
    fn every_protocol_key_has_a_winit_code() {
        let mapped: Vec<Key> = ALL.iter().filter_map(|&c| key_for(c)).collect();
        for k in Key::ALL {
            assert!(mapped.contains(k), "{k:?} unreachable");
        }
        assert_eq!(key_for(KeyCode::KeyW).map(scancode), Some(0x11));
    }

    const ALL: &[KeyCode] = &[
        KeyCode::Escape,
        KeyCode::Digit1,
        KeyCode::Digit2,
        KeyCode::Digit3,
        KeyCode::Digit4,
        KeyCode::Digit5,
        KeyCode::Digit6,
        KeyCode::Digit7,
        KeyCode::Digit8,
        KeyCode::Digit9,
        KeyCode::Digit0,
        KeyCode::Minus,
        KeyCode::Equal,
        KeyCode::Backspace,
        KeyCode::Tab,
        KeyCode::KeyQ,
        KeyCode::KeyW,
        KeyCode::KeyE,
        KeyCode::KeyR,
        KeyCode::KeyT,
        KeyCode::KeyY,
        KeyCode::KeyU,
        KeyCode::KeyI,
        KeyCode::KeyO,
        KeyCode::KeyP,
        KeyCode::BracketLeft,
        KeyCode::BracketRight,
        KeyCode::Enter,
        KeyCode::ControlLeft,
        KeyCode::KeyA,
        KeyCode::KeyS,
        KeyCode::KeyD,
        KeyCode::KeyF,
        KeyCode::KeyG,
        KeyCode::KeyH,
        KeyCode::KeyJ,
        KeyCode::KeyK,
        KeyCode::KeyL,
        KeyCode::Semicolon,
        KeyCode::Quote,
        KeyCode::Backquote,
        KeyCode::ShiftLeft,
        KeyCode::Backslash,
        KeyCode::KeyZ,
        KeyCode::KeyX,
        KeyCode::KeyC,
        KeyCode::KeyV,
        KeyCode::KeyB,
        KeyCode::KeyN,
        KeyCode::KeyM,
        KeyCode::Comma,
        KeyCode::Period,
        KeyCode::Slash,
        KeyCode::ShiftRight,
        KeyCode::NumpadMultiply,
        KeyCode::AltLeft,
        KeyCode::Space,
        KeyCode::CapsLock,
        KeyCode::F1,
        KeyCode::F2,
        KeyCode::F3,
        KeyCode::F4,
        KeyCode::F5,
        KeyCode::F6,
        KeyCode::F7,
        KeyCode::F8,
        KeyCode::F9,
        KeyCode::F10,
        KeyCode::F11,
        KeyCode::F12,
        KeyCode::NumLock,
        KeyCode::ScrollLock,
        KeyCode::Numpad0,
        KeyCode::Numpad1,
        KeyCode::Numpad2,
        KeyCode::Numpad3,
        KeyCode::Numpad4,
        KeyCode::Numpad5,
        KeyCode::Numpad6,
        KeyCode::Numpad7,
        KeyCode::Numpad8,
        KeyCode::Numpad9,
        KeyCode::NumpadSubtract,
        KeyCode::NumpadAdd,
        KeyCode::NumpadDecimal,
        KeyCode::NumpadDivide,
        KeyCode::NumpadEnter,
        KeyCode::IntlBackslash,
        KeyCode::ControlRight,
        KeyCode::PrintScreen,
        KeyCode::AltRight,
        KeyCode::Home,
        KeyCode::ArrowUp,
        KeyCode::PageUp,
        KeyCode::ArrowLeft,
        KeyCode::ArrowRight,
        KeyCode::End,
        KeyCode::ArrowDown,
        KeyCode::PageDown,
        KeyCode::Insert,
        KeyCode::Delete,
        KeyCode::SuperLeft,
        KeyCode::SuperRight,
        KeyCode::ContextMenu,
    ];
}
